---
- name: Include variables
  include_vars:
    file: main.yml

- name: Set up some system packages
  include: packages.yml
  
- name: Set up the gopher challenge
  include: gopher.yml

- name: Set up the web site
  include: sandy_website.yml

- name: Set up the Coin Miner
  include: coinminer.yml
