---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: hotpeppersec
    hostname: hotpeppersec
    image: ubuntu:latest
    # Do note that running containers in privileged mode is considerably less secure.
    privileged: true
    security_opts:
      - seccomp=unconfined
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    tmpfs:
      - /tmp
      - /run
    capabilities:
      - SYS_ADMIN
    exposed_ports:
      - 80/udp
      - 80/tcp
    published_ports:
      - 0.0.0.0:8080:80/udp
      - 0.0.0.0:8080:80/tcp
    ulimits:
      - nofile:262144:262144
    dns_servers:
      - 8.8.8.8
    command: '/lib/systemd/systemd'
provisioner:
  name: ansible
  log: true
scenario:
  become: true
  test_sequence:
    - destroy
    - create
    - prepare
    - converge
    - verify
    - destroy
verifier:
  name: testinfra
  env:
    PYTHONWARNINGS: "ignore:.*U.*mode is deprecated:DeprecationWarning"
