---
- name: "Create home directory for scoreboard cloning"
  file:
    path: "{{ home_directory }}"
    state: directory

- git:
    repo: 'https://github.com/CTFd/CTFd.git'
    dest: "{{ home_directory }}"
