---
sudo: required
dist: xenial   # required for Python >= 3.7
language: python
services: 
  - docker
python:
  - "3.8"
before_install:
  - sudo apt-get -qq update
  - python3 -m pip install wheel
  - python3 -m pip install -rpython/requirements.txt
script: 
  - cd playbooks/roles/webserver && molecule test
