apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: scoreboard-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: secops-ctf-scoreboard
        environment: dev
    spec:
      containers:
      - name: scoreboard-deployment
        image: us.gcr.io/ctf-sko21/secops-ctf-scoreboard:v1
        ports:
        - containerPort: 80
