---
  name: Packer
  
  on:
    push:
  
  jobs:
    packer:
      runs-on: ubuntu-latest
      name: packer
  
      steps:
        - name: Checkout Repository
          uses: actions/checkout@v2
  
        # fix backwards incompatibilities in template
        - name: Fix Template
          uses: operatehappy/packer-github-actions@master
          with:
            command: fix
            target: scoreboard.json
  
        # validate templates
        - name: Validate Template
          uses: operatehappy/packer-github-actions@master
          with:
            command: validate
            arguments: -syntax-only
            target: scoreboard.json
  
        # build artifact
        - name: Build Artifact
          uses: operatehappy/packer-github-actions@master
          with:
            command: build
            target: scoreboard.json
            arguments: "-color=false -on-error=abort"
  
        # additional steps to process artifacts